In [1]:
import numpy as np


In [3]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
arr = np.array([[1, 2], [3, 4]]).flatten()
arr

array([1, 2, 3, 4])

In [7]:
arr = np.array([[1,2],[4,5]])
arr

array([[1, 2],
       [4, 5]])

In [9]:
arr = np.array([[1,2],[4,5]]).transpose()
arr

array([[1, 4],
       [2, 5]])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
arr3 = np.concatenate((arr1,arr2))
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [27]:
arr = np.arange(6)
result = np.split(arr, 3)
result

[array([0, 1]), array([2, 3]), array([4, 5])]

In [29]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.vstack((arr1, arr2))
result

array([[1, 2],
       [3, 4]])

In [31]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.hstack((arr1, arr2))
result

array([1, 2, 3, 4])