In [23]:
import numpy as np

In [27]:
arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr > 2)
print(result)

(array([2, 3, 4], dtype=int64),)


In [29]:
result = np.unique(arr)
print(result)  

[1 2 3 4 5]


In [31]:
result = np.unique(np.array([1,2,3,3,4,5,2]))
print(result)  

[1 2 3 4 5]


In [33]:
result = np.sort(arr)
print(result)

[1 2 3 4 5]


In [37]:
arr = np.full((2, 2), 7) 
arr


array([[7, 7],
       [7, 7]])

In [41]:
arr = np.random.randint(0, 10, (3, 3)) 
arr

array([[9, 1, 5],
       [1, 0, 0],
       [6, 7, 5]])

In [43]:
arr = np.random.normal(0, 1, (2, 2))
arr

array([[ 3.49360596, -0.50441595],
       [ 0.11402122, -0.7423483 ]])

In [45]:
arr = np.diag([1, 2, 3]) 
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])