In [1]:
import numpy as np

In [3]:
arr_int8 = np.array([1, -2, 127], dtype=np.int8)
arr_int8

array([  1,  -2, 127], dtype=int8)

In [13]:
arr = np.array([1000, -2000, 32767], dtype=int)
arr

array([ 1000, -2000, 32767])

In [17]:
arr.dtype

dtype('int32')

In [32]:
arr = np.array([1, 3, 5], dtype=np.uint8)
arr

array([1, 3, 5], dtype=uint8)

In [34]:
arr_int = np.array([-10, 0, 10, 127, -128], dtype=np.int8)
arr_uint = arr_int.astype(np.uint8)
arr_uint

array([246,   0,  10, 127, 128], dtype=uint8)

In [36]:
arr = np.array([1, 2, 3], dtype=np.float32)
arr

array([1., 2., 3.], dtype=float32)

In [40]:
arr_float = np.array([1, 2, 3], dtype=np.float64)
arr_float

array([1., 2., 3.])

In [42]:
arr = np.array([1 + 2j, 3 + 4j], dtype=np.complex128)
arr


array([1.+2.j, 3.+4.j])

In [44]:
arr_bool = np.array([True, False, True], dtype=np.bool_)
arr_bool

array([ True, False,  True])

In [48]:
arr = np.array([1, "two", 3.0, [4, 5]], dtype=object)
arr

array([1, 'two', 3.0, list([4, 5])], dtype=object)

In [50]:
arr[1]

'two'

In [56]:
arr[3][1]

5

In [58]:
dates = np.array(['2023-10-01', '2023-10-02', '2023-10-03'], dtype='datetime64')
dates

array(['2023-10-01', '2023-10-02', '2023-10-03'], dtype='datetime64[D]')