In [1]:
import numpy as np


In [3]:
result = np.add([1, 2], [3, 4])
result

array([4, 6])

In [5]:
result = np.subtract([5, 6], [1, 2])
result

array([4, 4])

In [7]:
result = np.multiply([1, 2], [3, 4])
result

array([3, 8])

In [9]:
result = np.divide([6, 8], [2, 4])
result

array([3., 2.])

In [11]:

result = np.dot([1, 2], [3, 4])
result

11

In [13]:
result = np.sum([1, 2, 3])
result

6

In [15]:
result = np.mean([1, 2, 3])
result

2.0

In [17]:
result = np.std([1, 2, 3])
result

0.816496580927726

In [19]:
result = np.min([1, 2, 3])
result

1

In [21]:
result = np.max([1, 2, 3])
result

3