In [1]:
import numpy as np

In [5]:
mat = np.array([[1, 2], [3, 4]])
inv_mat = np.linalg.inv(mat)
inv_mat

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
det = np.linalg.det(mat)
det

-2.0000000000000004

In [11]:
eigenvalues, eigenvectors = np.linalg.eig(mat)
eigenvalues

array([-0.37228132,  5.37228132])

In [13]:
eigenvectors

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [15]:
x = np.linalg.solve(mat, [5, 11])
x

array([1., 2.])

In [17]:
print("Statistical Functions")

Statistical Functions


In [19]:
result = np.median([1, 2, 3, 4])
result

2.5

In [21]:
result = np.percentile([1, 2, 3, 4], 50)
result

2.5