In [3]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [28]:
arr = np.empty((2,3))
arr

array([[6.23042070e-307, 1.33512376e-306, 1.11261230e-306],
       [7.56577399e-307, 9.34600963e-307, 1.05699581e-307]])

In [30]:
arr

array([[6.23042070e-307, 1.33512376e-306, 1.11261230e-306],
       [7.56577399e-307, 9.34600963e-307, 1.05699581e-307]])

In [34]:
arr=np.arange(0,10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [51]:

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
arr = np.random.rand(2, 2)
print(arr)

[[0.55844821 0.08588467]
 [0.48256085 0.02428756]]


In [13]:
arr = np.empty((2,3))
arr

array([[1.50589680e+161, 5.85218931e+199, 1.27616420e-152],
       [5.28757355e+180, 6.37304048e+270, 2.25294965e-310]])

In [19]:
arr = np.logspace(0, 2, 5)
print(arr)

[  1.           3.16227766  10.          31.6227766  100.        ]
